#!/bin/bash

VIMGO_SRC_DIR="${HOME}/.vim_go_runtime"
VIMGO_RC_FILE="${HOME}/.vimrc.go"

#
#  setup vimgo.
#
function _vimgo_setup() {
  if [ ! -d "${VIMGO_SRC_DIR}" ]; then
    git clone git@github.com:farazdagi/vim-go-ide.git "${VIMGO_SRC_DIR}"
  fi

  if [ ! -f "${VIMGO_RC_FILE}" ]; then
    sh "${VIMGO_SRC_DIR}"/bin/install
  fi

}  #  End of function  _vimgo_setup.


#  vimgo.
function vimgo() {
  #  Ensure vimgo is setup.
  _vimgo_setup

  vim -u "${VIMGO_RC_FILE}" "$@"

}  #  End of function  vimgo.

#
#  Setup go paths.
#
function _setup_go_paths() {
  export GOROOT=/usr/local/go
  export GOPATH=/home/ramr/work/golang
  alias cdreaper='cd ${GOPATH}/src/github.com/ramr/go-reaper'
  alias cdrp='cdreaper'
  alias cdtelegraph='cd ${GOPATH}/src/github.com/ramr/go-grpc-telegraph'
  alias cdt='cdtelegraph'
  alias cdtele='cdtelegraph'
  alias cdg='cdtelegraph'

  export PATH=/usr/local/go/bin:${PATH}:${GOPATH}/bin

}  #  End of function  _setup_go_paths.


#
#  _main_:
#
_setup_go_paths
