#!/bin/bash

#  rm/cp/mv aliases
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

#  ls variants.
alias ls='ls -NF'
alias lsa='ls -aNF'

#  git.
alias got='git'
alias authors="git log --format='%aN' | sort -u"
alias reset2master="echo 'Run command: git reset --hard remotes/origin/HEAD'";
alias undolast="echo 'Run command: git reset --soft HEAD^'"
alias git_co_main="get_git_main_branch_name | xargs -I %b git checkout %b"
alias updsrc="update_git_sources"

#  misc.
alias mkvmerge='/Applications/Mkvtoolnix-7.0.0.app/Contents/MacOS/mkvmerge'
alias hinv='lshw'
alias ohfck='sudo $(history -p \!\!)' 
alias fck='eval $(thefuck $(fc -ln -1))'
alias extip='echo "$(curl http://ipecho.net/plain)"'
alias getdl='go get -u github.com/derekparker/delve/cmd/dlv'
alias todo='todo.sh'
alias dug='dig +noall +answer'

#  alias dl='docker ps -l -q'

alias pwgen="openssl rand -base64 20"

#  VM aliases.
alias vm="ssh ramr@tahr"
alias osvm="vagrant ssh"
