#!/bin/bash

#  rm/cp/mv aliases
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

#  ls variants.
alias ls='ls -F'
alias lsa='ls -aF'

#  git.
alias got='git'
alias authors="git log --format='%aN' | sort -u"
alias reset2master="echo 'Run command: git reset --hard remotes/origin/HEAD'";
alias undolast="echo 'Run command: git reset --soft HEAD^'"
alias updsrc="git fetch upstream; git co master; git rebase upstream/master"

#  misc.
alias vers='sw_vers'
alias mkvmerge='/Applications/Mkvtoolnix-7.0.0.app/Contents/MacOS/mkvmerge'
alias hinv='system_profiler'
alias ohfck='sudo $(history -p \!\!)' 
alias fck='eval $(thefuck $(fc -ln -1))'

#  alias dl='docker ps -l -q'


#  VM aliases.
alias vm="ssh ramr@tahr"
alias osvm="vagrant ssh"
