#!/bin/bash


function _ensure_git_completions() {
  local mydir
  mydir=$(cd -P -- "$(dirname "${BASH_SOURCE[0]}")" && pwd)
  local gitcompletion=${1:-"${mydir}/downloads/completions.git"}

  if [ ! -f "${gitcompletion}" ]; then
    echo "  - Downloading git completions ... "
    curl -q -s -k -L https://git.io/vfhol > "${gitcompletion}"
  fi

  return 0

}  #  End of function  _ensure_git_completions.


function _setup_completions() {
  local mydir
  mydir=$(cd -P -- "$(dirname "${BASH_SOURCE[0]}")" && pwd)
  local gitcfg="${mydir}/downloads/completions.git"

  _ensure_git_completions  "${gitcfg}"

  # shellcheck disable=SC1090
  source "${gitcfg}"

}  #  End of function  _setup_completions.


#
_setup_completions
