#!/bin/bash

# key bindings

#
#  Set a gnome schema specific key.
#
#  Usage:  _gset <schema> <key> [ <value> ]
#
#  Examples:
#    _gset org.gnome.desktop.wm.keybindings close "['<Alt>W']"
#
#    _gset org.gnome.desktop.wm.keybindings close
#
function _gset() {
  [ -n "$1" ] && [ -n "$2" ] && gsettings set "$1" "$2" "${3-''}"

}  #  End of function  _gset.


#
#  Setup elementary OS specific key bindings.
#
#  Usage:  _setup_key_bindings
#
#  Examples:
#    _setup_key_bindings
#
function _setup_key_bindings() {
  _gset org.gnome.desktop.wm.keybindings panel-main-menu "['<Alt>space', '<Alt>F2']"
  _gset org.gnome.desktop.wm.keybindings activate-window-menu "['<Super>space']"
  _gset org.freedesktop.ibus.general.hotkey triggers "['<Alt>space']"

  _gset org.gnome.desktop.wm.keybindings close "['<Alt>W']"
  _gset org.gnome.desktop.wm.keybindings show-desktop "['<Alt>Down']"

  _gset org.pantheon.desktop.gala.keybindings switch-to-workspace-first "['<Alt>Home', '<Alt>KP_Home']"
  _gset org.gnome.desktop.wm.keybindings switch-to-workspace-left "['<Super>Left']"
  _gset org.gnome.desktop.wm.keybindings switch-to-workspace-right "['<Super>Right']"

  _gset org.pantheon.terminal.settings foreground '#424242'
  _gset org.pantheon.terminal.settings background 'rgb(250,250,250)'

  _gset org.gnome.desktop.wm.keybindings toggle-maximized "['<Shift><Alt>f']"
  _gset org.gnome.desktop.wm.keybindings minimize "['<Alt>m']"

}  #  End of function  _setup_key_bindings.


#
#  Elementary OS specific setup.
#
#  Usage:  _eos_setup
#
#  Examples:
#    _eos_setup
#
function _eos_setup() {
  _setup_key_bindings

}  #  End of function  _eos_setup.


#
#  main():
#
_eos_setup
