#!/bin/bash


function open() {
  if [ -z "$1" ] || [ "$1" == "." ] || [ "$1" == "Finder" ]; then
    xdg-open .
    return $?
  else
    if [ "$1" == "xterm" ]; then
      local termapp=${_desktop_terminal_app:-""}
      if [ -n "${termapp}" ]; then
	shift
        ${termapp} "$@"
        return $?
      fi
    fi
  fi

  xdg-open "$@"

}  #  End of function  open.


function old_kernel_loadwaitinfo() {
  # From  brendangregg.com
  awk 'NF > 7 { if ($1 == "task") { if (h == 0) { print; h=1 } } else { print } }' /proc/sched_debug

}  #  End of function old_kernel_loadwaitinfo.


function _setup_elementary_os() {
  _desktop_file_app=$(which pantheon-files)
  export _desktop_file_app
  _desktop_terminal_app=$(which pantheon-terminal)
  export _desktop_terminal_app

  alias Finder="pantheon-files"
  alias xterm="pantheon-terminal"

}  #  End of function  _setup_elementary_os.


function _setup_linux_aliases() {
  alias ntpupdate="sync-ntp-time"
  alias pkgcleanup="sudo apt-get autoremove"

  local distid
  distid=$(lsb_release -si)
  if type _setup_"${distid}"_os > /dev/null 2>&1 ; then
    _setup_"${distid}"_os
  fi

}  #  End of function  _setup_linux_aliases.


#
#  main():
#
_setup_linux_aliases
