#!/bin/bash

# set -o posix


function _macosx__setup_aliases() {
  alias hinv="system_profiler"
  alias hinv-ports="networksetup -listallhardwareports"

  alias vers='sw_vers'

  alias airport="/System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport"
  alias wifi-info="airport -I"
  alias wifi-disconnect="airport -z"

  alias spindump-off="spindumpctl off > /dev/null 2>&1"

}  #  End of function  _macosx__setup_aliases.


function _macosx__setup_bash_completion() {
  local bc="$(brew --prefix)/etc/bash_completion)"
  [ -f "$bc" ]  &&  source "$bc"

}  #  End of function _macosx__setup_bash_completion


#
#  main():
#
_macosx__setup_aliases
_macosx__setup_bash_completion
