#!/bin/bash


function sshjump {
  expect -c "
spawn -noecho ssh -X -A $1;
send \"ssh -X $2\\r\";
send \"cdos\\r\";
interact -o eof return
"

}  #  End of function  sshjump.


function rrhc() { 
   "$(which rhc)" "$@" -p "$(cat ~/.openshift/.pc)";

}  #  End of function  rhc.


function _setup_bash_completion() {
    if [ -f /etc/bash_completion ]; then
          . /etc/bash_completion
            fi

}


#
#  main():
#
_setup_bash_completion
