#!/bin/bash


function sshjump {
    expect -c "
spawn -noecho ssh -X -A $1;
send \"ssh -X $2\\r\";
send \"cdos\\r\";
interact -o eof return
"

}  #  End of function  sshjump.


function rrhc() { 
    "$(which rhc)" "$@" -p "$(cat ~/.openshift/.pc)";

}  #  End of function  rhc.


function tldr() {
    curl "https://cht.sh/$1"

}  #  End of function  tldr.


function _setup_bash_completion() {
    if [ -f /etc/bash_completion ]; then
	    # shellcheck source=/dev/null
	    source /etc/bash_completion
    fi

}  #  End of function  _setup_bash_completion.


#
#  main():
#
_setup_bash_completion
