#!/bin/bash

#  VirtualBox manage.
alias vmgr='VBoxManage'

# kubectl krew
export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"


#  Load RVM into a shell session *as a function*
# shellcheck disable=SC1090
[[ -s "${HOME}/.rvm/scripts/rvm" ]] && source "${HOME}/.rvm/scripts/rvm"

PATH=${PATH}:${HOME}/.rvm/bin # Add RVM to PATH for scripting


#  Load NVM into a shell session and use default ... 
if [ -s "${HOME}/.nvm/nvm.sh" ]; then
  source "${HOME}/.nvm/nvm.sh"
  # nvm use v12.7.0
  nvm use v8.15.0
fi
