#!/bin/bash

#  VirtualBox manage.
alias vmgr='VBoxManage'

#  Load RVM into a shell session *as a function*
# shellcheck disable=SC1090
[[ -s "${HOME}/.rvm/scripts/rvm" ]] && source "${HOME}/.rvm/scripts/rvm"

PATH=${PATH}:${HOME}/.rvm/bin # Add RVM to PATH for scripting


#  Load NVM into a shell session and use default ... 
#  [[ -s "${HOME}/.nvm/nvm.sh" ]] && source "${HOME}/.nvm/nvm.sh"
#  nvm use 0.12.5
