#!/bin/sh

if (test $# -lt 1); then
   echo "Usage: $0 <file>"
   exit 0;
fi

TMP_FILE="/tmp/$(basename "$0").$$"
for f in "$@"; do
   echo "@@@ --- Checking file $f ..."
   perl -pe 's#\r\n#\n#' "$f" > "$TMP_FILE"
   python -c "compile(open('$TMP_FILE').read(), '$TMP_FILE', 'exec')" 
   echo "@@@ --- Completed checking file $f "
   echo ""
done

rm -f "$TMP_FILE"
