#!/bin/bash

readonly SCRIPT_NAME=$0


function _shell_script_check() {
  if [ $# -lt 1 ]; then
     echo "Usage: $SCRIPT_NAME [<files>]"
     exit 0
  fi

  for f in "$@"; do
    if [[ "${IGNORE_FILES}" == *"$f"* ]]; then
      echo "  - File $f in ignore list, skipping ..."
    else
      shellcheck "$f"
    fi
  done

}  #  End of function  _shell_script_check.


#
#  main():
#
_shell_script_check "$@"
