#!/bin/bash

readonly SCRIPT_NAME=$0


function _search() {
  if [ $# -lt 1 ]; then
     echo "Usage: $SCRIPT_NAME <search-string-or-pattern> [<dirs-or-files>]"
     exit 0
  fi

  local pattern=$1
  shift

  local search_args=$*
  if [ -z "${search_args}" ]; then
     search_args="."
  fi

  grep -r "${pattern}" ${search_args} 2>&1 |   \
    grep -v "^grep:" | grep -v ".svn/"

}  #  End of function  _search.


#
#  main():
#
_search "$@"
