#!/bin/bash
set -Eeuo pipefail

function get_msg() {
   cd /home/ramr/workarea/vostok/trunk
   svn log --verbose -c "$1"
   svn diff -c "$1"
}


#
#  main():
#
if (test $# -ne 1); then
   echo "Usage: $(basename "$0") <revision>";
   exit -1;
fi

if  echo "$1" | grep "^[0-9][0-9]*$" > /dev/null 2>&1; then
   :
else
   echo "Revision $1 is not numeric."
   echo ""
   echo "Usage: $(basename "$0") <revision>";
   exit -1;
fi


get_msg "$1"
